package org.arpit.java2blog.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Borrowers generated by hbm2java
 */
@Entity
@Table(name = "borrowers")
public class Borrowers implements java.io.Serializable {

	private Integer borrowerId;
	private Borrowertype borrowerType;
	private Integer librariansByCreatedby;
	private Integer librariansByUpdatedby;
	private String schoolId;
	private String firstName;
	private String lastName;
	private String barCode;
	private Boolean gender;
	private String email;
	private String phoneNumber;
	private String address;
	private String avatar;
	private Boolean status;
	private Date createdDate;
	private Date updatedDate;
	private Set<Borrowings> borrowingses = new HashSet<Borrowings>(0);
	private Set<Returnings> returningses = new HashSet<Returnings>(0);

	public Borrowers() {
	}

	public Borrowers(Borrowertype borrowertype, Integer librariansByCreatedby, Integer librariansByUpdatedby) {
		this.borrowerType = borrowertype;
		this.librariansByCreatedby = librariansByCreatedby;
		this.librariansByUpdatedby = librariansByUpdatedby;
	}

	public Borrowers(Borrowertype borrowertype, Integer librariansByCreatedby, Integer librariansByUpdatedby,
			String schoolid, String firstname, String lastname, String barcode, Boolean gender, String email,
			String phonenumber, String address, String avatar, Boolean status, Date createddate, Date updateddate,
			Set<Borrowings> borrowingses, Set<Returnings> returningses) {
		this.borrowerType = borrowertype;
		this.librariansByCreatedby = librariansByCreatedby;
		this.librariansByUpdatedby = librariansByUpdatedby;
		this.schoolId = schoolid;
		this.firstName = firstname;
		this.lastName = lastname;
		this.barCode = barcode;
		this.gender = gender;
		this.email = email;
		this.phoneNumber = phonenumber;
		this.address = address;
		this.avatar = avatar;
		this.status = status;
		this.createdDate = createddate;
		this.updatedDate = updateddate;
		this.borrowingses = borrowingses;
		this.returningses = returningses;
	}
	public Borrowers( Integer librariansByCreatedby, Integer librariansByUpdatedby,
			String schoolid, String firstname, String lastname, String barcode, Boolean gender, String email,
			String phonenumber, String address, Boolean status, Date createddate, Date updateddate) {
		
		this.librariansByCreatedby = librariansByCreatedby;
		this.librariansByUpdatedby = librariansByUpdatedby;
		this.schoolId = schoolid;
		this.firstName = firstname;
		this.lastName = lastname;
		this.barCode = barcode;
		this.gender = gender;
		this.email = email;
		this.phoneNumber = phonenumber;
		this.address = address;
		this.status = status;
		this.createdDate = createddate;
		this.updatedDate = updateddate;
		this.borrowingses = null;
		this.returningses = null;
	}
	
	public Borrowers(Integer borrowerId,Integer librariansByCreatedby, Integer librariansByUpdatedby,
			String schoolid, String firstname, String lastname, String barcode, Boolean gender, String email,
			String phonenumber, String address, Boolean status, Date createddate, Date updateddate) {
		
		this.borrowerId=borrowerId;
		this.librariansByCreatedby = librariansByCreatedby;
		this.librariansByUpdatedby = librariansByUpdatedby;
		this.schoolId = schoolid;
		this.firstName = firstname;
		this.lastName = lastname;
		this.barCode = barcode;
		this.gender = gender;
		this.email = email;
		this.phoneNumber = phonenumber;
		this.address = address;
		this.status = status;
		this.createdDate = createddate;
		this.updatedDate = updateddate;
		this.borrowingses = null;
		this.returningses = null;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BORROWERID", unique = true, nullable = false)
	public Integer getBorrowerid() {
		return this.borrowerId;
	}

	public void setBorrowerid(Integer borrowerid) {
		this.borrowerId = borrowerid;
	}

	@ManyToOne
	@JoinColumn(name = "BORROWERTYPEID", nullable = false)
	public Borrowertype getBorrowertype() {
		return this.borrowerType;
	}

	public void setBorrowertype(Borrowertype borrowertype) {
		this.borrowerType = borrowertype;
	}

	@Column(name="CreatedBy")
	public Integer getLibrariansByCreatedby() {
		return this.librariansByCreatedby;
	}

	public void setLibrariansByCreatedby(Integer librariansByCreatedby) {
		this.librariansByCreatedby = librariansByCreatedby;
	}

	@Column(name="UpdatedBy")
	public Integer getLibrariansByUpdatedby() {
		return this.librariansByUpdatedby;
	}

	public void setLibrariansByUpdatedby(Integer librariansByUpdatedby) {
		this.librariansByUpdatedby = librariansByUpdatedby;
	}

	@Column(name = "SCHOOLID")
	public String getSchoolid() {
		return this.schoolId;
	}

	public void setSchoolid(String schoolid) {
		this.schoolId = schoolid;
	}

	@Column(name = "FIRSTNAME")
	public String getFirstname() {
		return this.firstName;
	}

	public void setFirstname(String firstname) {
		this.firstName = firstname;
	}

	@Column(name = "LASTNAME")
	public String getLastname() {
		return this.lastName;
	}

	public void setLastname(String lastname) {
		this.lastName = lastname;
	}

	@Column(name = "BARCODE")
	public String getBarcode() {
		return this.barCode;
	}

	public void setBarcode(String barcode) {
		this.barCode = barcode;
	}

	@Column(name = "GENDER")
	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONENUMBER")
	public String getPhonenumber() {
		return this.phoneNumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phoneNumber = phonenumber;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "AVATAR")
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}
	@DateTimeFormat(pattern = "yyyy-mm-dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 10)
	public Date getCreateddate() {
		return this.createdDate;
	}

	public void setCreateddate(Date createddate) {
		this.createdDate = createddate;
	}
	
	@DateTimeFormat(pattern = "yyyy-mm-dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 10)
	public Date getUpdateddate() {
		return this.updatedDate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updatedDate = updateddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "borrowers")
	public Set<Borrowings> getBorrowingses() {
		return this.borrowingses;
	}

	public void setBorrowingses(Set<Borrowings> borrowingses) {
		this.borrowingses = borrowingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "borrowers")
	public Set<Returnings> getReturningses() {
		return this.returningses;
	}

	public void setReturningses(Set<Returnings> returningses) {
		this.returningses = returningses;
	}

}
