package org.arpit.java2blog.model;
// Generated Dec 12, 2017 12:14:03 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Titleauthors generated by hbm2java
 */
@Entity
@Table(name = "titleauthors")
public class TitleAuthors implements java.io.Serializable {

	private Integer titleAuthorId;
	private Authors authors;
	private Titles titles;

	public TitleAuthors() {
	}
	
	public TitleAuthors(Integer titleAuthorId) {
		this.titleAuthorId = titleAuthorId;
	}

	public TitleAuthors(Authors authors, Titles titles) {
		this.authors = authors;
		this.titles = titles;
	}
	
	public TitleAuthors(Integer titleAuthorId,Authors authors, Titles titles) {
		this.titleAuthorId= titleAuthorId;
		this.authors = authors;
		this.titles = titles;
		this.authors.setTitleauthorses(null);
		this.titles.setBookses(null);
		this.titles.setTitleauthorses(null);
		this.titles.setCoursebookses(null);
		this.titles.setTitlecategorieses(null);
		this.titles.getPublishers().setTitleses(null);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TITLEAUTHORID", unique = true, nullable = false)
	public Integer getTitleauthorid() {
		return this.titleAuthorId;
	}

	public void setTitleauthorid(Integer titleauthorid) {
		this.titleAuthorId = titleauthorid;
	}

	@ManyToOne
	@JoinColumn(name = "AUID", nullable = false)
	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	@ManyToOne
	@JoinColumn(name = "TITLEID", nullable = false)
	public Titles getTitles() {
		return this.titles;
	}

	public void setTitles(Titles titles) {
		this.titles = titles;
	}

}
